### ISSUE TITLE
[BU] Arrow is not hidden when the user scrolls down.

### ISSUE THREAD

**Issue by abitsalihu** [devvsakib/hackerboi#11]
**Describe the bug**
The `arrow` does not disappear when the `user` scrolls down, because it is not defined in the DOM element.

**Screenshots**
`VIDEO of the bug happening:`

https://user-images.githubusercontent.com/94648837/195570517-c63e8e00-8d92-4f0c-9530-fbb70181c763.mov

**Additional context**
I would like to be assigned to this issue so I could solve it. :)

**Comment by devvsakib** [comment]
solved by #12
