### ISSUE TITLE
[HIGH] combine all the css file into one css file 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#13]
It's a good practice to put all reusable CSS into one file. Please merge all the CSS into one CSS file. And separate CSS according to page, like, for contribution page create contribution.css .

**Comment by vikash485** [comment]
Hey @devvsakib, please assign me this issue. I would like to contribute

**Comment by devvsakib** [comment]
> Hey @devvsakib, please assign me this issue. I would like to contribute

assigned

**Comment by devvsakib** [comment]
solved by #15
