### ISSUE TITLE
[FEATURE] imporve contributons page design

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#17]
**IMPROVE DESIGN**
it's time to improve our contributor's page design.
Design Sample:
![image](https://user-images.githubusercontent.com/88339569/195631504-1b3a6783-0551-47ca-87bd-41f149fee883.png)

please comment if you want to assign.

**Comment by jsvigneshkanna** [comment]
please assign this to me, will implement it

**Comment by devvsakib** [comment]
> please assign this to me, will implement it

assigned

**Comment by devvsakib** [comment]
solved by #19
