### ISSUE TITLE
LOCK ovarlay not working

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#27]
**Describe the bug**
When we first go to our website, we should not able to scroll or view anything excluding LOCK overlay, but here you can see everything without unlocking the website. There was an image background on the lock page.
![image](https://user-images.githubusercontent.com/88339569/197124801-b772a68d-90dc-4e88-9452-41bef12fb05c.png)

**To Reproduce**
hide body overflow to hidden,
after unlock, set body overflow to auto,
figure out why background not showing

**Expected behavior**
am animated background will show here
![image](https://user-images.githubusercontent.com/88339569/197125077-83222eca-c30a-4d3e-b151-1cbd048cdb80.png)
 people will unable to see the website and scroll until they unlock it. 

hacktoberfest label

**Comment by RXBlade** [comment]
Hey @devvsakib, I fixed this issue on branch https://github.com/RXBlade/hackerboi/tree/LOCK-ovarlay-not-working-%2327
Hope is exactly what you meant in the issue.

**Comment by devvsakib** [comment]
> Hey @devvsakib, I fixed this issue on branch https://github.com/RXBlade/hackerboi/tree/LOCK-ovarlay-not-working-%2327
> Hope is exactly what you meant in the issue.

marged with hacktoberfest label
