### ISSUE TITLE
create 3file named faq.html faq.css faq.js

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#33]
We have source code, you just have to create these 3file.
faq.html
faq.css
faq.js

and link them

### where is source code?
We have a FAQ file, open it, you will see css html js code there, seperate all code in their desire file

**Comment by Frey0-0** [comment]
I will do this @devvsakib

**Comment by devvsakib** [comment]
> I will do this @devvsakib 

assigned

**Comment by Frey0-0** [comment]
@devvsakib I have raised a PR for this issue. Please review and suggest changes if any.

**Comment by devvsakib** [comment]
> @devvsakib I have raised a PR for this issue. Please review and suggest changes if any.

done
