### ISSUE TITLE
fetch contributors details to contributors.html file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#37]
fetch all the data from contributors json file to contributors.html file
create a script.js file and fetch all data
comment if you are familiar with javascript fetch or map functions

**Comment by RXBlade** [comment]
Hey @devvsakib I'm on it!

**Comment by devvsakib** [comment]
> Hey @devvsakib I'm on it!

assigned

**Comment by MRIDUL-MB** [comment]
is it still open? if yes, can you assign me this?
