### ISSUE TITLE
[FEATURE] add nav to contributor page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#7]
add navbar to contributors page

**Comment by abitsalihu** [comment]
Hey @devvsakib, I would like to help with this issue. :)

**Comment by devvsakib** [comment]
> Hey @devvsakib, I would like to help with this issue. :)

suree

**Comment by abitsalihu** [comment]
@devvsakib I noticed there is errors with the opacity of the arrow in the `JS`? Should i fix this as well while I fix the other nav.

**Comment by devvsakib** [comment]
> @devvsakib I noticed there is errors with the opacity of the arrow in the `JS`? Should i fix this as well while I fix the other nav.

sure, create an issue and solve the error, I will label the issue as hacktoberfest

**Comment by abitsalihu** [comment]
@devvsakib alright, I will make the issue after I finish the navbar.

btw would you like the `nav bar` to be custom made or be the same as it is in the landing page with bootstrap?

**Comment by devvsakib** [comment]
> @devvsakib alright, I will make the issue after I finish the navbar.
> 
> btw would you like the `nav bar` to be custom made or be the same as it is in the landing page with bootstrap?

i like the solution. we should try

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by devvsakib** [comment]
> please assign me this issue

assigned
