### ISSUE TITLE
[FEATURE] create a custom navbar for index

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hackerboi#9]
create a custom navbar instead using bootstrap template in inedx.html file

**Comment by azeddine011** [comment]
Hey @devvsakib , I would like to help with this issue. :)

**Comment by inbuilt-aura** [comment]
Hey @devvsakib , i am new to the hacktoberfest, can you assign me this issue.I would love to contribute.

**Comment by anshit-2003** [comment]
Hey! i'd like to work on this issue could you please assign this issue to me 
I'm new to hacktoberfest

**Comment by devvsakib** [comment]
@anshit-2003  assigned and there are so many issue you can solve and PR. you should try

**Comment by devvsakib** [comment]
> Hey @devvsakib , i am new to the hacktoberfest, can you assign me this issue.I would love to contribute.

done and look for more issues and if you have suggestion please create an issue, so i will label the issue as hacktoberfest

**Comment by inbuilt-aura** [comment]
@devvsakib hey,can you tell me what extra you want in your website?

**Comment by devvsakib** [comment]
> @devvsakib hey,can you tell me what extra you want in your navbar website?

this is issue is completed
